package io.github.zukkari.checks

import io.github.zukkari.RuleSpec
import org.sonar.plugins.java.api.JavaFileScannerContext
import org.sonar.plugins.java.api.tree.ClassTree

class DataClassRuleSpec extends RuleSpec {
  val context: JavaFileScannerContext = mock[JavaFileScannerContext]
  val classTree: ClassTree = mock[ClassTree]

  val rule = new DataClassRule

  it should "detect simple data class with getters and setters" in {
    verifyRule(rule, "DataClassWithGetters")
  }

  it should "detect data class without getters and setters and public fields" in {
    verifyRule(rule, "DataClass")
  }

  it should "detect inner data classes" in {
    verifyRule(rule, "DataClassInner")
  }

  it should "detect non-standard setters (those not generated by the IDE)" in {
    verifyRule(rule, "DataClassCustomSetter")
  }

  override def dir: String = "data_class"
}
