package io.github.zukkari.checks

import io.github.zukkari.BaseSpec
import org.sonar.java.checks.verifier.JavaCheckVerifier
import org.sonar.plugins.java.api.JavaFileScannerContext
import org.sonar.plugins.java.api.tree.ClassTree

class DataClassRuleSpec extends BaseSpec {
  val context: JavaFileScannerContext = mock[JavaFileScannerContext]
  val classTree: ClassTree = mock[ClassTree]

  val rule = new DataClassRule

  it should "detect simple data class with getters and setters" in {
    verify("DataClassWithGetters")
  }

  it should "detect data class without getters and setters and public fields" in {
    verify("DataClass")
  }

  it should "detect inner data classes" in {
    verify("DataClassInner")
  }

  it should "detect non-standard setters (those not generated by the IDE)" in {
    verify("DataClassCustomSetter")
  }

  def verify(className: String): Unit = {
    JavaCheckVerifier.verify(s"src/test/resources/files/data_class/${className}.java", new DataClassRule())
  }
}
